#!/bin/tcsh -xef

# echo "Calculate mean motion"

# to execute via tcsh: 
#   tcsh -xef mean_motion_calculation |& tee output.mean_motion_calculation
# to execute via bash: 
#   tcsh -xef mean_motion_calculation 2>&1 | tee output.mean_motion_calculation

set processed_dir = "/blue/amandaelton/ch.yu/BYTE/subject_results/group.sst_batch/"
set outfile = "mean_motion.tsv"
echo "subject\tmotion" > $outfile

foreach subj ( `cat ${processed_dir}/folder.txt` )
    # Calculate the average motion
	set mot = `3dTstat -mean -prefix - $processed_dir/${subj}.results/motion_${subj}_enorm.1D\'`
    echo "${subj}\t${mot}" >> $processed_dir/$outfile
end