#!/bin/tcsh -xef

# to execute via tcsh: 
#   tcsh -xef copy_T1 |& tee output.copy_T1

# Make a list of subjects
# ls -d BYTE*/ | sed 's/\.results\///' > folders.txt

mkdir t1Mask

# Loop over subjects
foreach subj (`cat /blue/amandaelton/ch.yu/BYTE/subject_results/group.sst_batch/folder.txt`)
	echo ${subj}
    set anatDir = /blue/amandaelton/ch.yu/BYTE/subject_results/group.sst_batch/${subj}.results
	if (-d "$anatDir") then
		echo "Copying ${subj} mask_group+tlrc"
		3dcalc -a "$anatDir/mask_group+tlrc." -expr a -prefix "t1Mask/mask_group_${subj}.nii"
		3dcalc -a "$anatDir/*_pve_1.nii.gz" -expr 'step(a-0.05)' -prefix t1Mask/${subj}_0.05_gm
	else
		echo "$subj T1 missing, skipping."
	endif
end

# Make a group T1 mask
3dmask_tool -input t1Mask/mask_group_*.nii -prefix T1_mask_intersection+tlrc -union

# Make a group GM mask
# Combine all gm masks into a 4D file, with the 4th dimension being nth subject
3dTcat -prefix t1Mask/gm_mask_allSubject.nii t1Mask/*_0.05_gm*
3dTstat -prefix t1Mask/gm_mask_group_prob -mean t1Mask/gm_mask_allSubject.nii
# Make a group T1 mask with the voxels that 50% of the subjects have gm
3dcalc -overwrite -a t1Mask/gm_mask_group_prob+tlrc -expr 'step(a-0.5)' -prefix gm_mask_group


rm -r t1Mask