#!/bin/tcsh -xef

# to execute via tcsh: 
#   tcsh -xef BYTE_timing_convert |& tee output.BYTE_timing_convert6
# to execute via bash: 
#   tcsh -xef BYTE_timing_convert 2>&1 | tee output.BYTE_timing_convert

# SST
# 1st run onset: dummyScan.stopped
# 2nd run onset: dummyScan2.stopped
# Stimulus onset = goT.started - run onset 

# There are up to 7 event types for each emotional condition.
## ss: successful stop
## fs: failed stop
## pssgo: post-successful-stop correct go
## pfsgo: post-failed-stop correct go
## sgo: successful go no following stop
## fgo: any failed go (with response)
## miss: missed go
## I just realized that we are not able to account for the sequence of emotional condition, e.g., negative-pssgo can follow either negative or neutral

cd /orange/amandaelton/BYTE_raw
ls -d BYTE?? > /blue/amandaelton/ch.yu/BYTE/BYTE_timing/subjList.txt
# cd /blue/amandaelton/ch.yu/BYTE/BYTE_timing/sst_task_timing

# set events = ("ss" "fs" "pssgo" "pfsgo" "sgo" "fgo" "miss")
# set emotions = ("negative" "neutral")

# # foreach subj ( `cat ../subjList2.txt` )
# foreach subj ("BYTE02" "BYTE16" "BYTE18" "BYTE19" "BYTE23" "BYTE34" "BYTE56" "BYTE63" "BYTE71" "BYTE72" "BYTE75" "BYTE77" "BYTE78" "BYTE79" "BYTE80" "BYTE81")
	# foreach condition ($events)
		# foreach emotion ($emotions)
			# foreach run (1 2)
				# # Check if the CSV file exists; if not, skip to the next run
                # if ( ! -f "${subj}_sst_time_${emotion}_run${run}.csv" ) then
                    # echo "File missing, skipping: ${subj}_sst_time_${emotion}_run${run}.csv"
                    # continue
                # endif
				# echo ${subj}_sst_time_${emotion}_run${run}
				# awk -F', *' -v cond="$condition" 'NR>1 && $2==cond {print $1}' ${subj}_sst_time_${emotion}_run${run}.csv > \
				# ${subj}_sst_time_${emotion}_${condition}_run${run}.txt
				
				# timing_tool.py -fsl_timing_files ${subj}_sst_time_${emotion}_${condition}_run${run}.txt \
				# -write_timing ${subj}_sst_time_${emotion}_${condition}_run${run}.1D
			# end
			# # Combine only if BOTH run 1 and run 2 files exist
            # if ( -f "${subj}_sst_time_${emotion}_${condition}_run1.txt" && -f "${subj}_sst_time_${emotion}_${condition}_run2.txt" ) then
                # timing_tool.py -fsl_timing_files ${subj}_sst_time_${emotion}_${condition}_run*.txt \
                # -write_timing ${subj}_sst_time_${emotion}_${condition}.1D
            # else
                # echo "File missing, only one run found (or none) for ${subj} ${emotion} ${condition}. Skipping combination."
            # endif
		# end
	# end
# end


# Cyberball
# There are 9 event types for all subjects (Schulz et al., 2022 also have a "throw" event, but our event-related design may not be able to differentiate it from accept events, talk to Amanda later):
# Inclusion block (onset: dummyEnd.stopped): in_accept, in_notMyTurn, in_null
# Exclusion block (onset: dummyEnd.stopped): ex_accept, ex_reject, ex_null
# Re-inclusion block (onset: dummyEnd.stopped): rein_accept, rein_notMyTurn, rein_null

cd /blue/amandaelton/ch.yu/BYTE/BYTE_timing/cyber_task_timing

foreach subj ( `cat ../subjList.txt` )
    if ( -f "${subj}_cyberball_time_inclu.csv" ) then
        echo ${subj}_cyberball_time_inclu
        awk -F', *' -v type="_13" 'NR>1 && $4 ~ (type "$") {print $1}' ${subj}_cyberball_time_inclu.csv > ${subj}_cyberball_time_in_notMyTurn.txt
        timing_tool.py -fsl_timing_files ${subj}_cyberball_time_in_notMyTurn.txt -write_timing ${subj}_cyberball_time_in_notMyTurn.1D
        
        awk -F', *' -v type="_2" 'NR>1 && $4 ~ (type "$") {print $2}' ${subj}_cyberball_time_inclu.csv > ${subj}_cyberball_time_in_accept.txt
        timing_tool.py -fsl_timing_files ${subj}_cyberball_time_in_accept.txt -write_timing ${subj}_cyberball_time_in_accept.1D
        
        awk -F', *' -v type="_null" 'NR>1 && $4 ~ (type "$") {print $3}' ${subj}_cyberball_time_inclu.csv > ${subj}_cyberball_time_in_null.txt
        timing_tool.py -fsl_timing_files ${subj}_cyberball_time_in_null.txt -write_timing ${subj}_cyberball_time_in_null.1D
    else
        echo "Missing: ${subj}_cyberball_time_inclu.csv (skipping inclusion)"
    endif
	
    if ( -f "${subj}_cyberball_time_exclu.csv" ) then
        echo ${subj}_cyberball_time_exclu
        awk -F', *' -v type="_13" 'NR>1 && $4 ~ (type "$") {print $1}' ${subj}_cyberball_time_exclu.csv > ${subj}_cyberball_time_ex_notMyTurn.txt
        timing_tool.py -fsl_timing_files ${subj}_cyberball_time_ex_notMyTurn.txt -write_timing ${subj}_cyberball_time_ex_notMyTurn.1D
        
        awk -F', *' -v type="_2" 'NR>1 && $4 ~ (type "$") {print $2}' ${subj}_cyberball_time_exclu.csv > ${subj}_cyberball_time_ex_accept.txt
        timing_tool.py -fsl_timing_files ${subj}_cyberball_time_ex_accept.txt -write_timing ${subj}_cyberball_time_ex_accept.1D
        
        awk -F', *' -v type="_null" 'NR>1 && $4 ~ (type "$") {print $3}' ${subj}_cyberball_time_exclu.csv > ${subj}_cyberball_time_ex_null.txt
        timing_tool.py -fsl_timing_files ${subj}_cyberball_time_ex_null.txt -write_timing ${subj}_cyberball_time_ex_null.1D
    else
        echo "Missing: ${subj}_cyberball_time_exclu.csv (skipping exclusion)"
    endif

    if ( -f "${subj}_cyberball_time_reinclu.csv" ) then
        echo ${subj}_cyberball_time_reinclu
        awk -F', *' -v type="_13" 'NR>1 && $4 ~ (type "$") {print $1}' ${subj}_cyberball_time_reinclu.csv > ${subj}_cyberball_time_rein_notMyTurn.txt
        timing_tool.py -fsl_timing_files ${subj}_cyberball_time_rein_notMyTurn.txt -write_timing ${subj}_cyberball_time_rein_notMyTurn.1D
        
        awk -F', *' -v type="_2" 'NR>1 && $4 ~ (type "$") {print $2}' ${subj}_cyberball_time_reinclu.csv > ${subj}_cyberball_time_rein_accept.txt
        timing_tool.py -fsl_timing_files ${subj}_cyberball_time_rein_accept.txt -write_timing ${subj}_cyberball_time_rein_accept.1D
        
        awk -F', *' -v type="_null" 'NR>1 && $4 ~ (type "$") {print $3}' ${subj}_cyberball_time_reinclu.csv > ${subj}_cyberball_time_rein_null.txt
        timing_tool.py -fsl_timing_files ${subj}_cyberball_time_rein_null.txt -write_timing ${subj}_cyberball_time_rein_null.1D
    else
        echo "Missing: ${subj}_cyberball_time_reinclu.csv (skipping reinclusion)"
    endif
end

cd ..

# foreach subj (cat subjList.txt)
	# echo ${subj}
	# awk -F', *' 'NR>1 && $2=="ss" {print $1}' ${subj}_sst_run1.csv > ${subj}_ss_run1.txt
	# awk -F', *' 'NR>1 && $2=="fs" {print $1}' ${subj}_sst_run1.csv > ${subj}_fs_run1.txt
	# awk -F', *' 'NR>1 && $2=="pssgo" {print $1}' ${subj}_sst_run1.csv > ${subj}_pssgo_run1.txt
	# awk -F', *' 'NR>1 && $2=="pfsgo" {print $1}' ${subj}_sst_run1.csv > ${subj}_pfsgo_run1.txt
	# awk -F', *' 'NR>1 && $2=="1go" {print $1}' ${subj}_sst_run1.csv > ${subj}_1go_run1.txt
	# awk -F', *' 'NR>1 && $2=="missgo" {print $1}' ${subj}_sst_run1.csv > ${subj}_missgo_run1.txt
	# awk -F', *' 'NR>1 && $2=="fgo" {print $1}' ${subj}_sst_run1.csv > ${subj}_fgo_run1.txt
	# awk -F', *' 'NR>1 && $2=="pcggo" {print $1}' ${subj}_sst_run1.csv > ${subj}_pcggo_run1.txt
	# awk -F', *' 'NR>1 && $2=="pfggo" {print $1}' ${subj}_sst_run1.csv > ${subj}_pfggo_run1.txt
	
	# timing_tool.py -fsl_timing_files ${subj}_ss_run1.txt -write_timing ${subj}_ss_run1.1D
	# timing_tool.py -fsl_timing_files ${subj}_fs_run1.txt -write_timing ${subj}_fs_run1.1D
	# timing_tool.py -fsl_timing_files ${subj}_pssgo_run1.txt -write_timing ${subj}_pssgo_run1.1D
	# timing_tool.py -fsl_timing_files ${subj}_pfsgo_run1.txt -write_timing ${subj}_pfsgo_run1.1D
	# timing_tool.py -fsl_timing_files ${subj}_1go_run1.txt -write_timing ${subj}_1go_run1.1D
	# timing_tool.py -fsl_timing_files ${subj}_missgo_run1.txt -write_timing ${subj}_missgo_run1.1D
	# timing_tool.py -fsl_timing_files ${subj}_fgo_run1.txt -write_timing ${subj}_fgo_run1.1D
	# timing_tool.py -fsl_timing_files ${subj}_pcggo_run1.txt -write_timing ${subj}_pcggo_run1.1D
	# timing_tool.py -fsl_timing_files ${subj}_pfggo_run1.txt -write_timing ${subj}_pfggo_run1.1D
	
	# awk -F', *' 'NR>1 && $2=="ss" {print $1}' ${subj}_sst_run2.csv > ${subj}_ss_run2.txt
	# awk -F', *' 'NR>1 && $2=="fs" {print $1}' ${subj}_sst_run2.csv > ${subj}_fs_run2.txt
	# awk -F', *' 'NR>1 && $2=="pssgo" {print $1}' ${subj}_sst_run2.csv > ${subj}_pssgo_run2.txt
	# awk -F', *' 'NR>1 && $2=="pfsgo" {print $1}' ${subj}_sst_run2.csv > ${subj}_pfsgo_run2.txt
	# awk -F', *' 'NR>1 && $2=="1go" {print $1}' ${subj}_sst_run2.csv > ${subj}_1go_run2.txt
	# awk -F', *' 'NR>1 && $2=="missgo" {print $1}' ${subj}_sst_run2.csv > ${subj}_missgo_run2.txt
	# awk -F', *' 'NR>1 && $2=="fgo" {print $1}' ${subj}_sst_run2.csv > ${subj}_fgo_run2.txt
	# awk -F', *' 'NR>1 && $2=="pcggo" {print $1}' ${subj}_sst_run2.csv > ${subj}_pcggo_run2.txt
	# awk -F', *' 'NR>1 && $2=="pfggo" {print $1}' ${subj}_sst_run2.csv > ${subj}_pfggo_run2.txt
	
	# timing_tool.py -fsl_timing_files ${subj}_ss_run2.txt -write_timing ${subj}_ss_run2.1D
	# timing_tool.py -fsl_timing_files ${subj}_fs_run2.txt -write_timing ${subj}_fs_run2.1D
	# timing_tool.py -fsl_timing_files ${subj}_pssgo_run2.txt -write_timing ${subj}_pssgo_run2.1D
	# timing_tool.py -fsl_timing_files ${subj}_pfsgo_run2.txt -write_timing ${subj}_pfsgo_run2.1D
	# timing_tool.py -fsl_timing_files ${subj}_1go_run2.txt -write_timing ${subj}_1go_run2.1D
	# timing_tool.py -fsl_timing_files ${subj}_missgo_run2.txt -write_timing ${subj}_missgo_run2.1D
	# timing_tool.py -fsl_timing_files ${subj}_fgo_run2.txt -write_timing ${subj}_fgo_run2.1D
	# timing_tool.py -fsl_timing_files ${subj}_pcggo_run2.txt -write_timing ${subj}_pcggo_run2.1D
	# timing_tool.py -fsl_timing_files ${subj}_pfggo_run2.txt -write_timing ${subj}_pfggo_run2.1D
	
	# timing_tool.py -fsl_timing_files ${subj}_ss_run*.txt -write_timing ${subj}_ss.1D
	# timing_tool.py -fsl_timing_files ${subj}_fs_run*.txt -write_timing ${subj}_fs.1D
	# timing_tool.py -fsl_timing_files ${subj}_pssgo_run*.txt -write_timing ${subj}_pssgo.1D
	# timing_tool.py -fsl_timing_files ${subj}_pfsgo_run*.txt -write_timing ${subj}_pfsgo.1D
	# timing_tool.py -fsl_timing_files ${subj}_1go_run*.txt -write_timing ${subj}_1go.1D
	# timing_tool.py -fsl_timing_files ${subj}_missgo_run*.txt -write_timing ${subj}_missgo.1D
	# timing_tool.py -fsl_timing_files ${subj}_fgo_run*.txt -write_timing ${subj}_fgo.1D
	# timing_tool.py -fsl_timing_files ${subj}_pcggo_run*.txt -write_timing ${subj}_pcggo.1D
	# timing_tool.py -fsl_timing_files ${subj}_pfggo_run*.txt -write_timing ${subj}_pfggo.1D
# end
